import streamlit as st
import pandas as pd
import datetime
import os
import numpy as np
import time
from PIL import Image
from fpdf import FPDF
from database_utils import get_connection
from streamlit_drawable_canvas import st_canvas

if not os.path.exists("uploads"): os.makedirs("uploads")

def save_file(uploaded_file):
    if uploaded_file:
        path = os.path.join("uploads", uploaded_file.name)
        with open(path, "wb") as f: f.write(uploaded_file.getbuffer())
        return path
    return None

def generate_contract(booking_id, renter, vehicle, plate, chk_data, sig_r, sig_a, is_with_driver=False, driver_name=""):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", 'B', 16)
    pdf.cell(0, 10, "DRIVEELITE HANDOVER AGREEMENT", ln=True, align='C')
    pdf.set_font("Helvetica", '', 12)
    pdf.cell(0, 10, f"Ref: DRV-{booking_id:05d} | Date: {datetime.date.today()}", ln=True)
    pdf.cell(0, 10, f"Vehicle: {vehicle} ({plate})", ln=True)
    pdf.cell(0, 10, f"Renter: {renter}", ln=True)
    
    if is_with_driver and driver_name:
        pdf.cell(0, 10, f"Assigned Driver: {driver_name}", ln=True)
    
    pdf.ln(10)
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(0, 10, "VERIFIED CHECKLIST:", ln=True)
    
    pdf.set_font("Helvetica", '', 11)
    for item in chk_data: 
        pdf.cell(0, 8, f"[ OK ]  {item}", ln=True)
    
    current_y = pdf.get_y() + 10
    
    try:
        if sig_r is not None:
            Image.fromarray(sig_r.astype('uint8'), 'RGBA').convert('RGB').save("tr.jpg", "JPEG")
            pdf.image("tr.jpg", x=20, y=current_y, w=50)
        if sig_a is not None:
            Image.fromarray(sig_a.astype('uint8'), 'RGBA').convert('RGB').save("ta.jpg", "JPEG")
            pdf.image("ta.jpg", x=120, y=current_y, w=50)
    except Exception as e: pass
    
    sig_label = "Driver Signature" if is_with_driver else "Affiliate Signature"
    
    pdf.set_xy(20, current_y + 40)
    pdf.cell(50, 5, "Renter Signature", align='C')
    pdf.set_xy(120, current_y + 40)
    pdf.cell(50, 5, sig_label, align='C')
    
    pdf.ln(20)
    pdf.set_font("Helvetica", 'I', 9) 
    pdf.cell(0, 5, "Legally generated by DriveElite Platform", align='C')
    return pdf.output(dest="S").encode("latin-1")

def generate_return_receipt(booking_id, renter, vehicle, plate, fuel, clean, damage, late, ot_fee, rfid_fee, total_deduct, refund, sig_ret, sig_reta, is_with_driver=False, driver_name=""):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Helvetica", 'B', 16)
    pdf.cell(0, 10, "DRIVEELITE RETURN & SETTLEMENT RECEIPT", ln=True, align='C')
    pdf.set_font("Helvetica", '', 12)
    pdf.cell(0, 10, f"Ref: DRV-{booking_id:05d} | Date: {datetime.date.today()}", ln=True)
    pdf.cell(0, 10, f"Vehicle: {vehicle} ({plate})", ln=True)
    pdf.cell(0, 10, f"Renter: {renter}", ln=True)
    
    if is_with_driver and driver_name:
        pdf.cell(0, 10, f"Assigned Driver: {driver_name}", ln=True)
    
    pdf.ln(10)
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(0, 10, "SECURITY DEPOSIT DEDUCTIONS:", ln=True)
    pdf.set_font("Helvetica", '', 11)
    pdf.cell(0, 8, f"Fuel Replacement: Php {fuel:,.2f}", ln=True)
    pdf.cell(0, 8, f"Cleaning Fee: Php {clean:,.2f}", ln=True)
    pdf.cell(0, 8, f"Damage Penalty: Php {damage:,.2f}", ln=True)
    
    pdf.cell(0, 8, f"RFID Load Deducted: Php {rfid_fee:,.2f}", ln=True)
    pdf.cell(0, 8, f"Late Return Penalty: Php {late:,.2f}", ln=True)
    
    if is_with_driver:
        pdf.cell(0, 8, f"Driver Overtime Fee: Php {ot_fee:,.2f}", ln=True)
    
    pdf.ln(5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    
    pdf.set_font("Helvetica", 'B', 12)
    pdf.cell(0, 10, f"TOTAL DEDUCTIONS: Php {total_deduct:,.2f}", ln=True)
    pdf.cell(0, 10, f"FINAL REFUND TO RENTER: Php {refund:,.2f}", ln=True)
    
    current_y = pdf.get_y() + 15
    
    try:
        if sig_ret is not None:
            Image.fromarray(sig_ret.astype('uint8'), 'RGBA').convert('RGB').save("tret.jpg", "JPEG")
            pdf.image("tret.jpg", x=20, y=current_y, w=50)
        if sig_reta is not None:
            Image.fromarray(sig_reta.astype('uint8'), 'RGBA').convert('RGB').save("treta.jpg", "JPEG")
            pdf.image("treta.jpg", x=120, y=current_y, w=50)
    except Exception as e: pass
    
    sig_label = "Driver Final Sign-off" if is_with_driver else "Affiliate Final Sign-off"
    
    pdf.set_xy(20, current_y + 40)
    pdf.cell(50, 5, "Renter Final Sign-off", align='C')
    pdf.set_xy(120, current_y + 40)
    pdf.cell(50, 5, sig_label, align='C')
    
    pdf.ln(20)
    pdf.set_font("Helvetica", 'I', 9) 
    pdf.cell(0, 5, "Legally generated by DriveElite Platform", align='C')
    return pdf.output(dest="S").encode("latin-1")


st.set_page_config(page_title="Affiliate Portal", layout="wide")
conn = get_connection()

try:
    cat_df = pd.read_sql_query("SELECT name, default_price FROM vehicle_categories", conn)
    FIXED_RATES = dict(zip(cat_df['name'], cat_df['default_price']))
except: FIXED_RATES = {"Sedan": 1500.0} 

if not st.session_state.get('logged_in') or st.session_state.get('role') != 'AFFILIATE':
    st.markdown("<h2 style='text-align: center;'>💼 AFFILIATE LOGIN</h2>", unsafe_allow_html=True)
    with st.form("login"):
        u = st.text_input("Username")
        p = st.text_input("Password", type="password")
        if st.form_submit_button("LOGIN", use_container_width=True):
            user = pd.read_sql_query("SELECT * FROM users WHERE username=? AND password=? AND role='AFFILIATE'", conn, params=(u, p))
            if not user.empty:
                if user.iloc[0]['admin_status'] == 'PENDING': st.warning("Account pending Admin approval.")
                elif user.iloc[0]['admin_status'] == 'REJECTED': st.error("Account application rejected.")
                else:
                    st.session_state.logged_in, st.session_state.username, st.session_state.role = True, u, 'AFFILIATE'
                    st.rerun()
            else: st.error("Invalid credentials.")
    st.stop()

with st.sidebar:
    st.markdown("<h3 style='text-align: center;'>💼 Affiliate Rules</h3>", unsafe_allow_html=True)
    st.markdown("* *Safety:* Cars must be safe.\n* *Fee:* 15% Platform Fee.\n* *Checklist:* Mandatory Handover/Return signoffs.\n* *Visibility:* Manage in My Assets.")
    if st.button("🔒 LOGOUT", use_container_width=True):
        st.session_state.clear()
        st.rerun()

username = st.session_state.username
st.markdown("<h1 style='text-align: center;'>💼 COMMAND CENTER</h1>", unsafe_allow_html=True)

tabs = st.tabs(["BOOKINGS & HANDOVER", "MY ASSETS", "ADD ASSET", "ADD DRIVER"])

with tabs[0]:
    st.markdown("<h3 style='text-align: center;'>🟡 PENDING DISPATCH</h3>", unsafe_allow_html=True)
    pending = pd.read_sql_query("SELECT b.id, b.renter_username, b.with_driver, u.full_name as renter_fullname, v.make, v.model, v.plate FROM bookings b JOIN vehicles v ON b.vehicle_id = v.id JOIN users u ON b.renter_username = u.username WHERE v.owner_username = ? AND b.status = 'CONFIRMED'", conn, params=(username,))
    
    if pending.empty: st.info("No vehicles pending dispatch.")
    for _, t in pending.iterrows():
        with st.expander(f"START TRIP: {t['make']} {t['model']} ({t['plate']}) - Renter: {t['renter_fullname']}"):
            
            if f"contract_{t['id']}" in st.session_state:
                st.success("SUCCESS: Contract successfully generated! Please download it to your phone to share with the renter.")
                
                # --- THE FIX: NATIVE STREAMLIT DOWNLOAD BUTTON ---
                st.download_button(
                    label="📥 DOWNLOAD PDF CONTRACT",
                    data=st.session_state[f"contract_{t['id']}"],
                    file_name=f"Contract_DRV_{t['id']:05d}.pdf",
                    mime="application/pdf",
                    use_container_width=True
                )
                
                if st.button("FINISH & RELEASE VEHICLE (START TRIP)", key=f"fin_{t['id']}", type="primary", use_container_width=True):
                    imgs = st.session_state.get(f"imgs_{t['id']}", [None]*10)
                    ass_driver = st.session_state.get(f"drv_{t['id']}", "")
                    
                    conn.execute("""UPDATE bookings SET status = 'ONGOING', 
                                    front_img=?, back_img=?, left_img=?, right_img=?, 
                                    odometer_img=?, dseat_img=?, pseat_img=?, tire_img=?, trunk_img=?, actual_dl_img=?, assigned_driver=? 
                                    WHERE id = ?""", (*imgs, ass_driver, t['id']))
                    conn.commit()
                    
                    for k in [f"contract_{t['id']}", f"imgs_{t['id']}", f"drv_{t['id']}"]:
                        if k in st.session_state: del st.session_state[k]
                    
                    st.rerun()
            
            else:
                is_with_driver = t.get('with_driver', 0) == 1
                assigned_driver = ""
                can_proceed = True
                
                if is_with_driver:
                    st.warning("👨‍✈️ *DRIVER REQUIRED FOR THIS TRIP*")
                    my_drivers = pd.read_sql_query("SELECT first_name || ' ' || last_name as full_name FROM drivers WHERE owner_username = ? AND admin_status = 'APPROVED'", conn, params=(username,))
                    if my_drivers.empty:
                        st.error("⚠️ You do not have any APPROVED drivers! Register one in the 'ADD DRIVER' tab and ask Admin to approve them before releasing this car.")
                        can_proceed = False
                    else:
                        assigned_driver = st.selectbox("Assign a Driver for this trip:", my_drivers['full_name'].tolist(), key=f"d_sel_{t['id']}")

                if can_proceed:
                    st.markdown(f"*HANDOVER CONTRACT (Ref: DRV-{t['id']:05d})*")
                    st.write("*PRE-HANDOVER CHECKLIST*")
                    chk_col1, chk_col2 = st.columns(2)
                    with chk_col1:
                        chk_tank = st.checkbox("[ ] Full Tank", key=f"htank_{t['id']}")
                        chk_ac = st.checkbox("[ ] Aircon properly functioning", key=f"hac_{t['id']}")
                        chk_wiper = st.checkbox("[ ] Wipers properly functioning", key=f"hwiper_{t['id']}")
                    with chk_col2:
                        chk_exterior = st.checkbox("[ ] Car checked all around", key=f"hext_{t['id']}")
                        chk_seats = st.checkbox("[ ] Seats / Interior checked", key=f"hse_{t['id']}")
                        chk_deposit = st.checkbox("[ ] Php 5,000.00 Deposit Confirmed", key=f"hdep_{t['id']}")
                    
                    st.divider()
                    st.write("* PRE-DISPATCH PHOTOS (10 Mandatory Photos)**")
                    
                    p_c1, p_c2, p_c3 = st.columns(3)
                    with p_c1:
                        img_dl = st.file_uploader("1. Actual Driver's License", type=['jpg', 'png', 'jpeg'], key=f"p_dl_{t['id']}")
                        img_front = st.file_uploader("4. Front Exterior", type=['jpg', 'png', 'jpeg'], key=f"p_front_{t['id']}")
                        img_right = st.file_uploader("7. Right Exterior", type=['jpg', 'png', 'jpeg'], key=f"p_right_{t['id']}")
                        img_pseat = st.file_uploader("10. Passenger Seat", type=['jpg', 'png', 'jpeg'], key=f"p_pseat_{t['id']}")
                    with p_c2:
                        img_odo = st.file_uploader("2. Odometer/Dashboard", type=['jpg', 'png', 'jpeg'], key=f"p_odo_{t['id']}")
                        img_back = st.file_uploader("5. Back Exterior", type=['jpg', 'png', 'jpeg'], key=f"p_back_{t['id']}")
                        img_trunk = st.file_uploader("8. Inside Trunk", type=['jpg', 'png', 'jpeg'], key=f"p_trunk_{t['id']}")
                    with p_c3:
                        img_dseat = st.file_uploader("3. Driver Seat", type=['jpg', 'png', 'jpeg'], key=f"p_dseat_{t['id']}")
                        img_left = st.file_uploader("6. Left Exterior", type=['jpg', 'png', 'jpeg'], key=f"p_left_{t['id']}")
                        img_tire = st.file_uploader("9. Spare Tire", type=['jpg', 'png', 'jpeg'], key=f"p_tire_{t['id']}")

                    st.divider()
                    c1, c2 = st.columns(2)
                    with c1:
                        st.markdown("<div style='text-align: center;'><b>Renter Signature</b></div>", unsafe_allow_html=True)
                        if f"clr_sr_{t['id']}" not in st.session_state: st.session_state[f"clr_sr_{t['id']}"] = 0
                        _, mid1, _ = st.columns([1, 4, 1])
                        with mid1:
                            s_r = st_canvas(stroke_width=2, stroke_color="#000", background_color="#eee", height=150, width=250, display_toolbar=False, key=f"sr_{t['id']}_{st.session_state[f'clr_sr_{t['id']}']}")
                            if st.button("Clear / Erase", key=f"btn_sr_{t['id']}", use_container_width=True):
                                st.session_state[f"clr_sr_{t['id']}"] += 1; st.rerun()
                    with c2:
                        sig_label = "Driver Signature" if is_with_driver else "Affiliate Signature"
                        st.markdown(f"<div style='text-align: center;'><b>{sig_label}</b></div>", unsafe_allow_html=True)
                        
                        if f"clr_sa_{t['id']}" not in st.session_state: st.session_state[f"clr_sa_{t['id']}"] = 0
                        _, mid2, _ = st.columns([1, 4, 1])
                        with mid2:
                            s_a = st_canvas(stroke_width=2, stroke_color="#000", background_color="#eee", height=150, width=250, display_toolbar=False, key=f"sa_{t['id']}_{st.session_state[f'clr_sa_{t['id']}']}")
                            if st.button("Clear / Erase ", key=f"btn_sa_{t['id']}", use_container_width=True):
                                st.session_state[f"clr_sa_{t['id']}"] += 1; st.rerun()
                    
                    if st.button("GENERATE CONTRACT & PREPARE DISPATCH", key=f"ex_{t['id']}", type="primary", use_container_width=True):
                        has_sr = s_r.image_data is not None and len(s_r.json_data.get("objects", [])) > 0
                        has_sa = s_a.image_data is not None and len(s_a.json_data.get("objects", [])) > 0
                        all_10_photos = [img_front, img_back, img_left, img_right, img_odo, img_dseat, img_pseat, img_tire, img_trunk, img_dl]
                        
                        if not (chk_tank and chk_ac and chk_wiper and chk_exterior and chk_seats and chk_deposit): st.error("NOTICE: Check off all items.")
                        elif not all(all_10_photos): st.error("NOTICE: Upload all 10 Pre-Dispatch photos.")
                        elif not (has_sr and has_sa): st.error("NOTICE: Signatures required.")
                        else:
                            chk_items = ["Full Tank", "Aircon properly functioning", "Wipers properly functioning", "Car checked all around", "Seats / Interior checked", "Php 5,000.00 Deposit Confirmed"]
                            try:
                                pdf_bytes = generate_contract(t['id'], t['renter_fullname'], f"{t['make']} {t['model']}", t['plate'], chk_items, s_r.image_data, s_a.image_data, is_with_driver, assigned_driver)
                                
                                # THE FIX: Store the raw bytes, do not base64 encode!
                                st.session_state[f"contract_{t['id']}"] = pdf_bytes
                                st.session_state[f"imgs_{t['id']}"] = [save_file(img) for img in all_10_photos]
                                st.session_state[f"drv_{t['id']}"] = assigned_driver
                                st.rerun()
                            except Exception as e: st.error(f"Error: {str(e)}")

    st.divider()
    st.markdown("<h3 style='text-align: center;'>🔵 ONGOING TRIPS (Returns & Settlement)</h3>", unsafe_allow_html=True)
    
    ongoing = pd.read_sql_query("SELECT b.id, b.vehicle_id, b.renter_username, b.with_driver, b.assigned_driver, u.full_name as renter_fullname, v.make, v.model, v.plate FROM bookings b JOIN vehicles v ON b.vehicle_id = v.id JOIN users u ON b.renter_username = u.username WHERE v.owner_username = ? AND b.status = 'ONGOING'", conn, params=(username,))
    
    if ongoing.empty: st.info("No vehicles currently on the road.")
    for _, t in ongoing.iterrows():
        with st.expander(f"RECEIVE RETURN: {t['make']} {t['model']} ({t['plate']}) - Renter: {t['renter_fullname']}"):
            
            is_with_driver = t.get('with_driver', 0) == 1
            assigned_driver = t.get('assigned_driver', "")
            
            if f"ret_receipt_{t['id']}" in st.session_state:
                refund_amt = st.session_state[f"refund_{t['id']}"]
                st.success(f"SUCCESS: Settlement calculated! Final Refund: Php {refund_amt:,.2f}")
                
                # --- THE FIX: NATIVE STREAMLIT DOWNLOAD BUTTON ---
                st.download_button(
                    label="📥 DOWNLOAD SETTLEMENT PDF",
                    data=st.session_state[f"ret_receipt_{t['id']}"],
                    file_name=f"Settlement_DRV_{t['id']:05d}.pdf",
                    mime="application/pdf",
                    use_container_width=True
                )
                
                if st.button("CLOSE BOOKING & RELEASE RENTER", key=f"fin_ret_{t['id']}", type="primary", use_container_width=True):
                    d_img_path = st.session_state.get(f"dmg_img_{t['id']}", None)
                    
                    conn.execute("UPDATE bookings SET amount = amount - ?, status = 'COMPLETED', damage_img = ? WHERE id = ?", (refund_amt, d_img_path, t['id']))
                    conn.execute("UPDATE vehicles SET booking_status = 'AVAILABLE' WHERE id = ?", (t['vehicle_id'],))
                    conn.commit()
                    
                    for k in [f"ret_receipt_{t['id']}", f"refund_{t['id']}", f"dmg_img_{t['id']}"]:
                        if k in st.session_state: del st.session_state[k]
                        
                    st.rerun()
            else:
                st.markdown(f"*RETURN SETTLEMENT (Ref: DRV-{t['id']:05d})*")
                st.write("Uncheck boxes to apply deductions against the Php 5,000.00 Security Deposit.")
                
                c1, c2 = st.columns(2)
                with c1:
                    f_ok = st.checkbox("Fuel OK", value=True, key=f"f_{t['id']}")
                    fuel_deduct = 0.0
                    if not f_ok: fuel_deduct = st.number_input("Fuel Refill Cost (Php)", min_value=0.0, step=100.0, key=f"f_cost_{t['id']}")
                    
                    c_ok = st.checkbox("Cleanliness OK", value=True, key=f"c_{t['id']}")
                    clean_deduct = 0.0
                    if not c_ok:
                        st.warning("NOTICE: Soiled Vehicle: Php 500.00 deduction applied.")
                        clean_deduct = 500.0
                        
                    r_ok = st.checkbox("RFID Balanced / Load OK", value=True, key=f"r_{t['id']}")
                    rfid_fee = 0.0
                    if not r_ok:
                        rfid_fee = st.number_input("RFID Load Used (Php)", min_value=0.0, step=100.0, key=f"r_cost_{t['id']}")
                        st.warning(f"NOTICE: RFID Load Deduction of Php {rfid_fee:,.2f} applied.")
                    
                    l_ok = st.checkbox("Returned on Time", value=True, key=f"l_{t['id']}")
                    late_deduct = 0.0
                    if not l_ok:
                        late_hrs = st.number_input("Hours Late", min_value=1, step=1, key=f"l_hrs_{t['id']}")
                        late_deduct = late_hrs * 250.0
                        st.warning(f"NOTICE: Late Penalty of Php {late_deduct:,.2f} applied.")
                    
                    ot_fee = 0.0
                    if is_with_driver:
                        ot_ok = st.checkbox("Driver Hours OK (No Overtime)", value=True, key=f"ot_chk_{t['id']}")
                        if not ot_ok:
                            ot_hrs = st.number_input("Driver Overtime Hours", min_value=1, step=1, key=f"ot_hrs_{t['id']}")
                            ot_fee = ot_hrs * 200.0
                            st.warning(f"NOTICE: Driver Overtime Fee of Php {ot_fee:,.2f} applied.")

                    d_ok = st.checkbox("No Damage Found", value=True, key=f"d_{t['id']}")
                    damage_deduct = 0.0
                    img_damage = None
                    if not d_ok:
                        st.error("NOTICE: Damage Reported! You MUST upload a photo.")
                        img_damage = st.file_uploader("Upload Photo of Damage", type=['jpg', 'png', 'jpeg'], key=f"p_dam_{t['id']}")
                        dam_type = st.radio("Damage Penalty Type", ["Per Panel (Php 4k/panel)", "Custom Repair Estimate"], key=f"d_type_{t['id']}")
                        if dam_type == "Per Panel (Php 4k/panel)":
                            panels = st.number_input("Number of Damaged Panels", min_value=1, step=1, key=f"d_pan_{t['id']}")
                            damage_deduct = panels * 4000.0
                        else:
                            damage_deduct = st.number_input("Repair Shop Estimate (Php)", min_value=0.0, step=500.0, key=f"d_est_{t['id']}")

                    total_deduct = fuel_deduct + clean_deduct + damage_deduct + late_deduct + ot_fee + rfid_fee
                    refund_amount = 5000.0 - total_deduct
                    
                    st.divider()
                    st.write(f"*Total Deductions:* Php {total_deduct:,.2f}")
                    if refund_amount < 0:
                        st.error(f"NOTICE: Deductions exceed deposit! Renter owes an additional Php {abs(refund_amount):,.2f}")
                        refund_amount = 0.0
                    else: st.info(f"*Deposit to Refund:* Php {refund_amount:,.2f}")

                with c2:
                    c_ret1, c_ret2 = st.columns(2)
                    with c_ret1:
                        st.markdown("<div style='text-align: center;'><b>Renter Final Sign-off</b></div>", unsafe_allow_html=True)
                        if f"clr_sret_{t['id']}" not in st.session_state: st.session_state[f"clr_sret_{t['id']}"] = 0
                        s_ret = st_canvas(stroke_width=2, stroke_color="#000", background_color="#eee", height=150, width=150, display_toolbar=False, key=f"sret_{t['id']}_{st.session_state[f'clr_sret_{t['id']}']}")
                        if st.button("Clear Renter", key=f"btn_sret_{t['id']}", use_container_width=True):
                            st.session_state[f"clr_sret_{t['id']}"] += 1; st.rerun()
                    
                    with c_ret2:
                        ret_sig_label = "Driver Sign-off" if is_with_driver else "Affiliate Sign-off"
                        st.markdown(f"<div style='text-align: center;'><b>{ret_sig_label}</b></div>", unsafe_allow_html=True)
                        if f"clr_sreta_{t['id']}" not in st.session_state: st.session_state[f"clr_sreta_{t['id']}"] = 0
                        s_reta = st_canvas(stroke_width=2, stroke_color="#000", background_color="#eee", height=150, width=150, display_toolbar=False, key=f"sreta_{t['id']}_{st.session_state[f'clr_sreta_{t['id']}']}")
                        if st.button("Clear Partner", key=f"btn_sreta_{t['id']}", use_container_width=True):
                            st.session_state[f"clr_sreta_{t['id']}"] += 1; st.rerun()
                
                if st.button("GENERATE SETTLEMENT & COMPLETE JOURNEY", key=f"comp_{t['id']}", type="primary", use_container_width=True):
                    has_sret = s_ret.image_data is not None and len(s_ret.json_data.get("objects", [])) > 0
                    has_sreta = s_reta.image_data is not None and len(s_reta.json_data.get("objects", [])) > 0
                    
                    if not d_ok and not img_damage: st.error("NOTICE: You must upload a photo of the damage before settling!")
                    elif has_sret and has_sreta:
                        try:
                            pdf_bytes = generate_return_receipt(t['id'], t['renter_fullname'], f"{t['make']} {t['model']}", t['plate'], fuel_deduct, clean_deduct, damage_deduct, late_deduct, ot_fee, rfid_fee, total_deduct, refund_amount, s_ret.image_data, s_reta.image_data, is_with_driver, assigned_driver)
                            
                            # THE FIX: Store the raw bytes!
                            st.session_state[f"ret_receipt_{t['id']}"] = pdf_bytes
                            st.session_state[f"refund_{t['id']}"] = refund_amount
                            st.session_state[f"dmg_img_{t['id']}"] = save_file(img_damage) if img_damage else None
                            st.rerun()
                        except Exception as e:
                            st.error(f"Error generating PDF: {str(e)}")
                    else: st.error("NOTICE: Both the Renter and the Affiliate/Driver must sign to settle the trip.")

with tabs[1]:
    st.markdown("<h3 style='text-align: center;'>MY FLEET CONTROLS</h3>", unsafe_allow_html=True)
    fleet = pd.read_sql_query("SELECT id, make, model, plate, booking_status, admin_status FROM vehicles WHERE owner_username = ?", conn, params=(username,))
    if fleet.empty: st.info("You haven't added any vehicles yet.")
    for _, c in fleet.iterrows():
        with st.expander(f"{c['make']} {c['model']} - Status: {c['booking_status']} (Admin: {c['admin_status']})"):
            if c['admin_status'] == 'APPROVED':
                if c['booking_status'] == 'AVAILABLE' and st.button("Hide Vehicle", key=f"h_{c['id']}"):
                    conn.execute("UPDATE vehicles SET booking_status = 'UNAVAILABLE' WHERE id = ?", (c['id'],))
                    conn.commit(); st.rerun()
                elif c['booking_status'] == 'UNAVAILABLE' and st.button("Repost Vehicle", key=f"s_{c['id']}"):
                    conn.execute("UPDATE vehicles SET booking_status = 'AVAILABLE' WHERE id = ?", (c['id'],))
                    conn.commit(); st.rerun()

with tabs[2]:
    st.markdown("<h3 style='text-align: center;'>REGISTER A VEHICLE</h3>", unsafe_allow_html=True)
    with st.form("add_v"):
        cat = st.selectbox("CATEGORY", list(FIXED_RATES.keys()))
        c1, c2 = st.columns(2)
        ma, mo = c1.text_input("MAKE (e.g. Nissan)"), c2.text_input("MODEL (e.g. Terra VE)")
        ye, pl = c1.text_input("YEAR"), c2.text_input("PLATE NUMBER")
        
        c3, c4 = st.columns(2)
        bn = c3.text_input("PAYOUT BANK NAME (e.g. BDO, BPI, GCash)")
        an = c4.text_input("ACCOUNT NUMBER")
        
        c5, c6, c7 = st.columns(3)
        vi = c5.file_uploader("1. Vehicle Photo", type=['jpg','png'])
        orc = c6.file_uploader("2. OR/CR Document", type=['jpg','png'])
        ins = c7.file_uploader("3. Comprehensive Insurance", type=['jpg','png'])
        
        if st.form_submit_button("SUBMIT FOR APPROVAL", type="primary"):
            if ma and mo and pl and bn and an and vi and orc and ins:
                conn.execute("INSERT INTO vehicles (owner_username, make, model, year, plate, bank_name, account_no, vehicle_img, or_cr_img, insurance_img, category, approved_price) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)", (username, ma.title(), mo.title(), ye, pl.upper(), bn, an, save_file(vi), save_file(orc), save_file(ins), cat, FIXED_RATES.get(cat,0)))
                conn.commit(); st.success("SUCCESS: Vehicle Submitted! Pending Admin Approval.")
            else: st.error("Please fill all fields and upload all 3 required documents.")

with tabs[3]:
    st.markdown("<h3 style='text-align: center;'>REGISTER A DRIVER</h3>", unsafe_allow_html=True)
    with st.form("add_d"):
        c1, c2, c3 = st.columns(3)
        df_first = c1.text_input("First Name").title()
        df_mid = c2.text_input("Middle Name").title()
        df_last = c3.text_input("Last Name").title()
        c4, c5 = st.columns(2)
        d_contact = c4.text_input("Contact Number")
        d_age = c5.number_input("Age", min_value=18, max_value=99, step=1)
        d_address = st.text_area("Full Address")
        is_owner = st.checkbox("I am the driver (Owner driving)")
        
        st.write("*Identity Verification (2 IDs Required)*")
        c6, c7 = st.columns(2)
        d_gov = c6.file_uploader("Upload Govt ID", type=['jpg','png'], key="dgov")
        d_lic = c7.file_uploader("Upload Professional Driver's License", type=['jpg','png'], key="dlic")
        
        if st.form_submit_button("SUBMIT DRIVER FOR APPROVAL", type="primary"):
            if df_first and df_last and d_contact and d_gov and d_lic:
                conn.execute("INSERT INTO drivers (owner_username, first_name, middle_name, last_name, age, address, contact_number, is_owner, license_img, govt_id_img, admin_status) VALUES (?,?,?,?,?,?,?,?,?,?, 'PENDING')", (username, df_first, df_mid, df_last, d_age, d_address, d_contact, 1 if is_owner else 0, save_file(d_lic), save_file(d_gov)))
                conn.commit(); st.success("SUCCESS: Driver Submitted! Pending Admin Approval.")
            else: st.error("Please fill all required fields and upload both IDs.")
            
    st.divider()
    st.markdown("<h3 style='text-align: center;'>MY REGISTERED DRIVERS</h3>", unsafe_allow_html=True)
    try:
        my_drivers = pd.read_sql_query("SELECT first_name, last_name, contact_number, admin_status FROM drivers WHERE owner_username = ?", conn, params=(username,))
        if not my_drivers.empty: st.dataframe(my_drivers, hide_index=True, use_container_width=True)
        else: st.info("No drivers registered yet.")
    except: pass
